### ISSUE TITLE
Showing SBOM files in the download page

### ISSUE THREAD

**Issue by oscerd** [apache/camel-website#1096]
Starting from 4.1.0 we are providing SBOM for some of our projects:

- Camel
- Camel-Quarkus
- Camel-Spring-Boot
- Camel-Kamelets

I think it would be good to show these files in the Download page.

The files are json and XML

https://repo1.maven.org/maven2/org/apache/camel/camel/4.1.0/ 

For example.

@zregvart do you think it is something we could add? We'll need to filter out some of the versions for this subprojects and only show the columns in particular versions.

**Comment by zregvart** [comment]
If we can have a cut-off date, similar to the sha256 transition and if there are SBOMs for all downloads, the list doesn't include Apache Camel-K Runtime and Apache Camel Kafka Connector, then this should not be too much work.

I'm curious, why not upload then to dist.apache.org, so they're signed?

**Comment by oscerd** [comment]
I think it's my fault, I added to the release process but I forgot to add them to the release guide adoc.

At this stage there is no SBOM generated for k-runtime and Ckc. I can add them and once we have everything released we could set a cutoff date.

Also I'm going to update the release guide about SBOM. Thanks for noticing and reporting.

**Comment by zregvart** [comment]
All good. I can try to put a draft PR for adding SBOMs to the downloads with what we have now. Probably over the weekend if I find the time...
