### ISSUE TITLE
Website preview action is broken

### ISSUE THREAD

**Issue by squakez** [apache/camel-website#1170]
Just happened in a couple of PR I did. This is the error trace:
```
parse error: Invalid numeric literal at line 1, column 2
Error: Process completed with exit code 4.
```

https://github.com/apache/camel-website/actions/runs/8537724107/job/23388903274

**Comment by zregvart** [comment]
See https://github.com/netlify/cli/issues/5977 and https://github.com/netlify/cli/pull/6362

**Comment by apupier** [comment]
it is going a bit further, there is no "error" reported but the generated comment does not contain the link to the preview website (the DEPLOY_URL in our script)
