### ISSUE TITLE
Default values are no longer shown in the options tables

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-website#649]
Looking at
https://camel.apache.org/components/latest/aws2-s3-component.html

Then all the default values are no longer in the table. This is on the pre-release version (eg main branch).

@djencks wonder if you have seen this too.

**Comment by djencks** [comment]
I think this is fixed in the preview of the syntax update, see https://pr-648--camel.netlify.app/components/latest/aws2-s3-component.html#_component_option_autoCreateBucket.
