### ISSUE TITLE
`camel-kamelets` links broken

### ISSUE THREAD

**Issue by squakez** [apache/camel-website#661]
It appears that links which contains `camel-kamelets` are wrongly redirected. Ie https://camel.apache.org/camel-kamelets/next/ is redirecting to https://camel.apache.org/camel-k/next/amelets/next/ which is a 404.

I think it can be related to the change in redirect rules introduced in 93b65c838b74da17ab6b7e3983ec6f0d998673bc wdyt @zregvart ?

**Comment by oscerd** [comment]
I think this is related to https://github.com/apache/camel-kamelets/commit/0b352d1020c6c0315eabc9ba9e4c8472b7d735fa

**Comment by djencks** [comment]
I disagree, I’m pretty sure it’s a rewrite rule problem.

**Comment by oscerd** [comment]
It was working yesterday.

**Comment by zregvart** [comment]
The rewrites didn't take into effect until the website was published, and that only happened recently. The rewrite rule doesn't account for camel-kamelets. Its a simple fix and I'll have it ready shortly.

**Comment by oscerd** [comment]
ah yeah, just noticed the green build is from today, so definitely not related.

**Comment by squakez** [comment]
Thanks @zregvart

**Comment by zregvart** [comment]
Should be okay now.
