### ISSUE TITLE
Assemble .htaccess file from static component, Antora generated .htaccess, and derived rules

### ISSUE THREAD

**Issue by djencks** [apache/camel-website#672]
This
- Uses Antora to generate an .htaccess file, including 302 redirects from latest to <latest>
- Generates some more 302 redirects, basically from <versionless> to <latest>
- Inserts the result into the static .htaccess

This allows us to:
- redirect from e.g. /components/activemq-component.html to /components/3.13.x/activemq-component.html
- drop the out of date 301s copied from an old camel-quarkus .htaccess
- use page-aliases everywhere.

I've updated test/redirect.sh to be correct and more complete and provided a script to run the httpd server easily.

**Comment by zregvart** [comment]
Resolved via #672
