### ISSUE TITLE
Add Java version to the release files and display on download page

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-website#681]
We need a column in the downloads for each of our projects, that has title Java
Then we can list the java version supported such as: 8, 11, 17 

Camel 2.x will be: 8
Camel 3.x will be: 8, 11

Camel Kafka Connector will be: 8, 11

All the others will be: 11

**Comment by davsclaus** [comment]
@zregvart we can add `jdk` to these files
https://raw.githubusercontent.com/apache/camel-website/main/content/releases/release-2.25.4.md

eg 

```
jdk: 8
```

In that 2.x file.

And then show it in these tables on the download page.

**Comment by davsclaus** [comment]
Since Camel 2.x will be EOL soon we can maybe do this start of next year, then we do not have to bother with Camel 2.x

**Comment by davsclaus** [comment]
But with some bash magic then it should also be possible to just add the jdk to all the release files

**Comment by davsclaus** [comment]
It could also be nice to have a graph like spring have with their support where you can see when it starts / ends etc.
<img width="906" alt="Screenshot 2021-11-19 at 11 21 55" src="https://user-images.githubusercontent.com/477100/142607026-a4e98a01-1581-4d52-92de-2f77c3d25aa7.png">

**Comment by davsclaus** [comment]
However that is for another ticket ;)

**Comment by zregvart** [comment]
There is a [preview](https://pr-684--camel.netlify.app/) for #684, I'd appreciate feedback on placement/wording. Key pages are:

- the [download page](https://pr-684--camel.netlify.app/download/)
- the [release note page](https://pr-684--camel.netlify.app/releases/release-3.11.3/#jdk)

**Comment by davsclaus** [comment]
Looks good, simple and elegant

**Comment by zregvart** [comment]
I think it’s a good first step. I merged the PR. Let’s see if folk have improvements to suggest once it’s published.
