### ISSUE TITLE
Show kamelets on the download page

### ISSUE THREAD

**Issue by djencks** [apache/camel-website#694]
Leaving the latest release off the download page strongly implies that the subproject has never been released and should only be used for camel development.  That was certainly my conclusion until quite recently.

**Comment by zregvart** [comment]
I agree, per [ASF policy](https://www.apache.org/legal/release-policy.html#artifacts) every release must be accompanied by a source release. Created https://github.com/apache/camel-kamelets/issues/590 to get that done in the Kamelets repository first.

**Comment by zregvart** [comment]
Archives [are available](https://dlcdn.apache.org/camel/camel-kamelets/).
