### ISSUE TITLE
Add link to Security Advisories more prominent

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-website#707]
This page
https://camel.apache.org/security/

Is not easy to find, we should have a link so end users easily can find the list of known security advisories for Camel

@zregvart maybe you have a good idea to improve this

**Comment by zregvart** [comment]
Would be easy to add a new top level navigation item. Something like this:
![Screenshot 2021-12-08 at 10-04-42 Apache Camel helps you integrate over 300 different systems ](https://user-images.githubusercontent.com/1306050/145180038-8055a6b8-5c41-4d07-93c7-9bf5da5cebf0.png)
