### ISSUE TITLE
Some pages are showing as 'white background' only

### ISSUE THREAD

**Issue by trickstyler** [apache/camel-website#718]
https://camel.apache.org/manual/getting-started.html
https://camel.apache.org/components/3.13.x/index.html
https://camel.apache.org/manual/writing-components.html

are all returning proper HTML but appear as white background...

Tried from multiple browsers (Chrome, Firefox, Edge)
and from multiple machines

other pages seem to look ok (homepage included)

**Comment by djencks** [comment]
I think the content is there, but far down the page, and not formatted properly.  My local build of the antora-3 upgrade looks ok, so perhaps the cache-busting #702/#712 change broke the css?

**Comment by zregvart** [comment]
Seems like the mapping for file to hashed versions now returns `undefined`.
