### ISSUE TITLE
Share buttons disappeared in Blog

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-website#722]
I noticed Share buttons disappeared from a blog article. Is this something intentional or because some work is in progress on the website?  Otherwise, I'd like to see them recovered.

https://camel.apache.org/blog/2021/12/api-management-infra/
<img src=https://user-images.githubusercontent.com/156692/146133282-ad447060-9921-48b8-9625-f515a96bcb34.png width=50%/>

**Comment by zregvart** [comment]
They're loading for me, also on https://live.browserstack.com, perhaps try reloading?

**Comment by tadayosi** [comment]
It turned out that an adblocker browser extension on my browser (Chrome) did the filtering against the icons. Disabling the extension for the website recovered them for me. Probably others who use an adblocker face the same issue.

I'll explore a bit on why the icons are filtered out.

**Comment by zregvart** [comment]
Interesting... I guess if the user/user-agent chooses to block we should not interfere with that decision. And it's a cat and mouse game trying to defeat ad blockers. Not sure we should invest a lot of effort into this.

**Comment by tadayosi** [comment]
Found the same issue here: https://github.com/FortAwesome/Font-Awesome/issues/1799

I agree. It's Adblock Plus' issue or feature. It has an option `Block social media icons tracking` that you can toggle on/off. Since the Camel website is 100% ad free, it most makes sense that we just turn off ad blockers on the site.

Closing.
