### ISSUE TITLE
Commit the built Antora ui bundle so it's always available

### ISSUE THREAD

**Issue by djencks** [apache/camel-website#732]
The local/partial build setup needs the Antora UI bundle to be available.

Building it locally is at best a nuisance and on MacOS requires running in Docker or running yarn install to set up native dependencies for MacOS rather than the checked-in linux versions.

Another solution was proposed in https://github.com/apache/camel-website/pull/537, along with some variants, but I believe publishing the UI bundle as proposed there is significantly more complex for every use of the bundle with no redeeming advantages.

I'm happy with just manually committing it whenever it changes and we notice, since the official builds and previews will continue to build it just before using it, but it would be even better for the PR build or jenkins build to open a PR when it notices that the UI bundle has changed.

**Comment by djencks** [comment]
PR #738.

**Comment by zregvart** [comment]
Resolved via #738
