### ISSUE TITLE
Tune image output for social links

### ISSUE THREAD

**Issue by squakez** [apache/camel-website#768]
Right now the result would be like this:
![image](https://user-images.githubusercontent.com/23169723/151192749-37632e70-eba6-4b97-82a1-c40d07334833.png)
We must work on improving the image (which is required to be 1080p to render automatically).

_Originally posted by @squakez in https://github.com/apache/camel-website/issues/767#issuecomment-1022310649_

**Comment by squakez** [comment]
Have a look at https://developers.facebook.com/docs/sharing/best-practices#images for possible solution

**Comment by squakez** [comment]
I think the problem is uniquely with Twitter that does not like `meta property` but prefers `meta name`: https://stackoverflow.com/a/66816822/10974363 - I will have a look later to see if we can include also `twitter:image` meta beside the `og:image`

**Comment by zregvart** [comment]
I don't think this is the issue, I think the `og:image` should be an [absolute URL](https://ogp.me/#structured), which it currently is not.

**Comment by squakez** [comment]
I'll make some experiment and use the validator to see [how it renders](https://cards-dev.twitter.com/validator) with all options highlighted in this issue.
