### ISSUE TITLE
Camel components doc page is scrolling when user is typing

### ISSUE THREAD

**Issue by mmuzikar** [apache/camel-website#790]
When user is typing in the searchbar the page scrolls a little bit, it's not horrible but it's kinda funny.
See gif: 
![Peek 2022-02-24 15-43](https://user-images.githubusercontent.com/46345469/155682349-e0349e77-d056-45a7-a1cf-9efb9fc832c7.gif)

**Comment by zregvart** [comment]
Thanks for reporting this, what browser are you using? I don't see this using Firefox 97.0 or Chromium 96.0.4664.110.

**Comment by mmuzikar** [comment]
Chromium 96.0.4664.110 and Firefox 93.0
