### ISSUE TITLE
invalid links in docs

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-website#819]
[check:links    ] Found invalid urls in components/next/sql-component.html:
[check:links    ] 	Fragment #sql-component-header-values at components/next/sql-component.html does not exist!
[check:links    ] Found invalid urls in components/next/mongodb-component.html:
[check:links    ] 	Fragment #_endpoint_header%3C/em%3Eid at components/next/mongodb-component.html does not exist!
[check:links    ] Found invalid urls in camel-k/next/configuration/dependencies.html:
[check:links    ] 	Fragment #configuring-registry at camel-k/next/cli/cli.html does not exist!
[check:links    ] Found invalid urls in camel-k/next/cli/cli.html:
[check:links    ] 	Fragment #configuring-registry at camel-k/next/installation/registry/registry.html does not exist!
[check:links    ] Found invalid urls in blog/2022/04/camel-textual-debug-0.1.0/index.html:
[check:links    ] 	Linked file at path blog/2022/04/camel-textual-debug-0.1.0/blog/2022/02/camel-textual-debug-eclipse-vscode does not exist!

**Comment by davsclaus** [comment]
@apupier i think the last link errors is in your new blog post

Then we have a camel-k issue, and then in mongodb and sql components

**Comment by davsclaus** [comment]
@essobedo is those component header-values related to your awesome work on exposing the headers? Maybe you know how to fix these 2 components

**Comment by apupier** [comment]
> @apupier i think the last link errors is in your new blog post

yes, I updated my Pull Request to fix it

**Comment by davsclaus** [comment]
@squakez there are some doc link errors in camel-k main branch ^^^

**Comment by squakez** [comment]
> @squakez there are some doc link errors in camel-k main branch ^^^

I'm on it, thanks for the warning.

**Comment by apupier** [comment]
remaining errors:
```
[check:links    ] Found invalid urls in components/next/sql-component.html:
[check:links    ] 	Fragment #sql-component-header-values at components/next/sql-component.html does not exist!
[check:links    ] Found invalid urls in components/next/mongodb-component.html:
[check:links    ] 	Fragment #_endpoint_header%3C/em%3Eid at components/next/mongodb-component.html does not exist!
```

**Comment by davsclaus** [comment]
I have attempted to fix these 2 and the mongodb is due to a header that starts with underscore
https://issues.apache.org/jira/browse/CAMEL-17931
