### ISSUE TITLE
java code blocks are hardly readable with some keywords in dark grey on black background

### ISSUE THREAD

**Issue by apupier** [apache/camel-website#862]
![Screenshot from 2022-06-22 10-30-47](https://user-images.githubusercontent.com/1105127/174982462-5feca2f6-3ae9-4184-b2d0-916311601af2.png)

**Comment by zregvart** [comment]
This only affects the preview on Netlify. There no content security policy is in place and inline CSS is allowed whereas on the camel.apache.org it is not. There was a discussion on the [dev mailing list](https://lists.apache.org/thread/r0sqtgd899fbn2f5cf1xoxhcw15t402l) about this.
