### ISSUE TITLE
3.18.x LTS not declared as LTS on Releases page

### ISSUE THREAD

**Issue by ncgisudo** [apache/camel-website#887]
As the title says, the 3.18.x LTS releases are not stated as LTS releases on the main Releases page,
This is contradictory to the 3.18.x announcement pages (and more) which do state it as an LTS release,

Camel Releases page:
https://camel.apache.org/releases/
![image](https://user-images.githubusercontent.com/61501522/185358308-8eefd4d7-8f30-447f-9a82-395bce718371.png)

Camel 3.18.0 Release page (note - same thing applies to 3.18.1 page):
https://camel.apache.org/releases/release-3.18.0/
![image](https://user-images.githubusercontent.com/61501522/185357876-4433b032-a500-4563-93a9-fa29ec4cef12.png)

**Comment by davsclaus** [comment]
@zregvart I wonder if you know what is wrong

**Comment by ncgisudo** [comment]
Thank you for fixing this :)
