### ISSUE TITLE
Yarn v4

### ISSUE THREAD

**Issue by mrienstra** [apache/camel-website#910]
_This is just a heads up, no action needed at this time._

https://github.com/apache/camel-website/pull/803 added:

```json
  "resolutions": {
    "chalk": "4.1.2"
  },
```

... to downgrade `chalk` due to https://github.com/yarnpkg/berry/issues/3843, which was fixed yesterday. The fix is available in `4.0.0-rc.22`. Run [`yarn set version canary`](https://yarnpkg.com/cli/set/version) if you want to try it. v4 release is still a little ways off ("may take a couple more months"), but:
>[...] what's in master is stable, and I'd recommend you to try it. The only notable difference with stable is that we reserve the right to land a couple more breaking changes in future RCs, but in terms of stability it's almost always better to use RCs than stable.

... according to https://github.com/yarnpkg/berry/discussions/4895

See https://github.com/yarnpkg/berry/issues/3591 for v4 breaking changes. I've seen two mentions of people stumbling over `enableGlobalCache` default changing from `false` to `true`. ([Google search: site:yarnpkg.com "enableGlobalCache"](https://www.google.com/search?q=site%3Ayarnpkg.com+%22enableGlobalCache%22))

PS: `chalk` v5 is a dependency through `hugo-extended` --> `log-symbols`, see https://npmgraph.js.org/?q=hugo-extended.

**Comment by davsclaus** [comment]
@zregvart wonder if you have seen this ticket?

**Comment by zregvart** [comment]
Not seeing the need to upgrade right now, though anyone is welcome to try and report their findings.

**Comment by mrienstra** [comment]
Update: the fix that adds support for the `package.json` `includes` field is also in the [Yarn `3.2.4` release](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.2.4).

(this is still not in any way urgent, just a heads up that you can drop the `chalk` fix from https://github.com/apache/camel-website/pull/803 when you upgrade Yarn to `3.2.4`)
